export const ADD_PRODUCT = 'ADD_PRODUCT';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const FETCH_BASKET = 'FETCH_BASKET';
export const REQUEST_BASKET = 'REQUEST_BASKET';
export const RECEIVE_BASKET = 'RECEIVE_BASKET';
export const FETCH_BASKET_ERROR = 'FETCH_BASKET_ERROR';

export const POST_BASKET_ITEM = 'POST_BASKET_ITEM';

